[book]
authors = ["Azriel Hoh"]
language = "en"
multilingual = false
src = "src"
title = "WASM It"

[preprocessor.graphviz]
command = "mdbook-graphviz"

[preprocessor.mermaid]
command = "mdbook-mermaid"

[output.html]
additional-css = ["mermaid/mermaid.css", "mermaid/additional.css"]
additional-js = ["mermaid/mermaid.min.js", "mermaid/mermaid-init.js"]
